CREATE TABLE ADMIN.TOKEN_PSW (
  CLAVE    BIGINT PRIMARY KEY NOT NULL         GENERATED ALWAYS AS IDENTITY ( START WITH 1 INCREMENT BY 1),
  token    VARCHAR(20)        NOT NULL,
  usuario  BIGINT             NOT NULL,
  usada    INT DEFAULT 0      NOT NULL,
  CREACION TIMESTAMP          NOT NULL         WITH DEFAULT CURRENT TIMESTAMP,
  MOD      TIMESTAMP          NOT NULL         GENERATED ALWAYS FOR EACH ROW ON UPDATE AS ROW CHANGE TIMESTAMP,
  FOREIGN KEY (usuario) REFERENCES admin.USUARIOS (clave)
);
