INSERT INTO WF_OBJ.DIAGRAMA_CONECCION (LABEL, NODO_ORIGEN_CL, POSICION_ANCLAJE_ORIGEN, NODO_DESTINO_CL, POSICION_ANCLAJE_DESTINO, CSS_CLASS)
VALUES (NULL, 1, 4, 10, 1, NULL);
INSERT INTO WF_OBJ.DIAGRAMA_CONECCION (LABEL, NODO_ORIGEN_CL, POSICION_ANCLAJE_ORIGEN, NODO_DESTINO_CL, POSICION_ANCLAJE_DESTINO, CSS_CLASS)
VALUES (NULL, 1, 3, 12, 1, NULL);
INSERT INTO WF_OBJ.DIAGRAMA_CONECCION (LABEL, NODO_ORIGEN_CL, POSICION_ANCLAJE_ORIGEN, NODO_DESTINO_CL, POSICION_ANCLAJE_DESTINO, CSS_CLASS)
VALUES (NULL, 1, 3, 14, 1, NULL);
INSERT INTO WF_OBJ.DIAGRAMA_CONECCION (LABEL, NODO_ORIGEN_CL, POSICION_ANCLAJE_ORIGEN, NODO_DESTINO_CL, POSICION_ANCLAJE_DESTINO, CSS_CLASS)
VALUES (NULL, 1, 3, 16, 1, NULL);
INSERT INTO WF_OBJ.DIAGRAMA_CONECCION (LABEL, NODO_ORIGEN_CL, POSICION_ANCLAJE_ORIGEN, NODO_DESTINO_CL, POSICION_ANCLAJE_DESTINO, CSS_CLASS)
VALUES (NULL, 1, 2, 18, 1, NULL);
INSERT INTO WF_OBJ.DIAGRAMA_CONECCION (LABEL, NODO_ORIGEN_CL, POSICION_ANCLAJE_ORIGEN, NODO_DESTINO_CL, POSICION_ANCLAJE_DESTINO, CSS_CLASS)
VALUES (NULL, 18, 3, 22, 1, NULL);
INSERT INTO WF_OBJ.DIAGRAMA_CONECCION (LABEL, NODO_ORIGEN_CL, POSICION_ANCLAJE_ORIGEN, NODO_DESTINO_CL, POSICION_ANCLAJE_DESTINO, CSS_CLASS)
VALUES (NULL, 18, 3, 24, 2, NULL);
INSERT INTO WF_OBJ.DIAGRAMA_CONECCION (LABEL, NODO_ORIGEN_CL, POSICION_ANCLAJE_ORIGEN, NODO_DESTINO_CL, POSICION_ANCLAJE_DESTINO, CSS_CLASS)
VALUES (NULL, 18, 3, 29, 2, NULL);
INSERT INTO WF_OBJ.DIAGRAMA_CONECCION (LABEL, NODO_ORIGEN_CL, POSICION_ANCLAJE_ORIGEN, NODO_DESTINO_CL, POSICION_ANCLAJE_DESTINO, CSS_CLASS)
VALUES (NULL, 22, 3, 26, 1, NULL);