INSERT INTO WF_OBJ.DIAGRAMA_NODOS (PROCESO_CL, TAREA_CL, LABEL, POSICION_X, POSICION_Y, CSS_CLASS)
VALUES (1, NULL, 'Definir Fondo', 35, 2, NULL);
INSERT INTO WF_OBJ.DIAGRAMA_NODOS (PROCESO_CL, TAREA_CL, LABEL, POSICION_X, POSICION_Y, CSS_CLASS)
VALUES (1, 1, 'Definir Fondo', 10, 10, NULL);
INSERT INTO WF_OBJ.DIAGRAMA_NODOS (PROCESO_CL, TAREA_CL, LABEL, POSICION_X, POSICION_Y, CSS_CLASS)
VALUES (1, 2, 'Construir RI', 10, 10, NULL);
INSERT INTO WF_OBJ.DIAGRAMA_NODOS (PROCESO_CL, TAREA_CL, LABEL, POSICION_X, POSICION_Y, CSS_CLASS)
VALUES (1, 3, 'Revisión RI', 10, 10, NULL);
INSERT INTO WF_OBJ.DIAGRAMA_NODOS (PROCESO_CL, TAREA_CL, LABEL, POSICION_X, POSICION_Y, CSS_CLASS)
VALUES (1, 4, 'Aprobación del Fondo por el Directorio', 10, 10, NULL);
INSERT INTO WF_OBJ.DIAGRAMA_NODOS (PROCESO_CL, TAREA_CL, LABEL, POSICION_X, POSICION_Y, CSS_CLASS)
VALUES (1, 5, 'Generar Boleta de Garantía y Cta Cte del Fondo', 10, 10, NULL);
INSERT INTO WF_OBJ.DIAGRAMA_NODOS (PROCESO_CL, TAREA_CL, LABEL, POSICION_X, POSICION_Y, CSS_CLASS)
VALUES (1, 6, 'Depositar Documentos en la SVS', 10, 10, NULL);
INSERT INTO WF_OBJ.DIAGRAMA_NODOS (PROCESO_CL, TAREA_CL, LABEL, POSICION_X, POSICION_Y, CSS_CLASS)
VALUES (1, 7, 'Difusión Comercial del Nuevo Fondo', 10, 10, NULL);
INSERT INTO WF_OBJ.DIAGRAMA_NODOS (PROCESO_CL, TAREA_CL, LABEL, POSICION_X, POSICION_Y, CSS_CLASS)
VALUES (1, 8, 'Coordinar Capacitaciones', 10, 10, NULL);
INSERT INTO WF_OBJ.DIAGRAMA_NODOS (PROCESO_CL, TAREA_CL, LABEL, POSICION_X, POSICION_Y, CSS_CLASS)
VALUES (2, NULL, 'Publicidad', 5, 12, NULL);
INSERT INTO WF_OBJ.DIAGRAMA_NODOS (PROCESO_CL, TAREA_CL, LABEL, POSICION_X, POSICION_Y, CSS_CLASS)
VALUES (2, 10, 'Publicidad', 10, 10, NULL);
INSERT INTO WF_OBJ.DIAGRAMA_NODOS (PROCESO_CL, TAREA_CL, LABEL, POSICION_X, POSICION_Y, CSS_CLASS)
VALUES (3, NULL, 'Apertura Custodio Extranjero', 20, 12, NULL);
INSERT INTO WF_OBJ.DIAGRAMA_NODOS (PROCESO_CL, TAREA_CL, LABEL, POSICION_X, POSICION_Y, CSS_CLASS)
VALUES (3, 12, 'Apertura de Cuenta Custodio Extranjero', 10, 10, NULL);
INSERT INTO WF_OBJ.DIAGRAMA_NODOS (PROCESO_CL, TAREA_CL, LABEL, POSICION_X, POSICION_Y, CSS_CLASS)
VALUES (4, NULL, 'Creación de Instrumento y Apertura en DCV', 35, 12, NULL);
INSERT INTO WF_OBJ.DIAGRAMA_NODOS (PROCESO_CL, TAREA_CL, LABEL, POSICION_X, POSICION_Y, CSS_CLASS)
VALUES (4, 14, 'Creación de Instrumento y Apertura en DCV', 10, 10, NULL);
INSERT INTO WF_OBJ.DIAGRAMA_NODOS (PROCESO_CL, TAREA_CL, LABEL, POSICION_X, POSICION_Y, CSS_CLASS)
VALUES (5, NULL, 'Aviso en Prensa', 50, 12, NULL);
INSERT INTO WF_OBJ.DIAGRAMA_NODOS (PROCESO_CL, TAREA_CL, LABEL, POSICION_X, POSICION_Y, CSS_CLASS)
VALUES (5, 16, 'Realizar Aviso Publicitario en Prensa', 10, 10, NULL);
INSERT INTO WF_OBJ.DIAGRAMA_NODOS (PROCESO_CL, TAREA_CL, LABEL, POSICION_X, POSICION_Y, CSS_CLASS)
VALUES (6, NULL, '1 Día antes del Lanzamiento', 65, 12, NULL);
INSERT INTO WF_OBJ.DIAGRAMA_NODOS (PROCESO_CL, TAREA_CL, LABEL, POSICION_X, POSICION_Y, CSS_CLASS)
VALUES (6, 18, 'Crear Fondo en el Sistema', 10, 10, NULL);
INSERT INTO WF_OBJ.DIAGRAMA_NODOS (PROCESO_CL, TAREA_CL, LABEL, POSICION_X, POSICION_Y, CSS_CLASS)
VALUES (6, 19, 'Ingresar Fondo en Contabilidad y UCC', 10, 10, NULL);
INSERT INTO WF_OBJ.DIAGRAMA_NODOS (PROCESO_CL, TAREA_CL, LABEL, POSICION_X, POSICION_Y, CSS_CLASS)
VALUES (6, 20, 'Día que ingresa Primera Inversión', 10, 10, NULL);
INSERT INTO WF_OBJ.DIAGRAMA_NODOS (PROCESO_CL, TAREA_CL, LABEL, POSICION_X, POSICION_Y, CSS_CLASS)
VALUES (7, NULL, 'Día de la Primera Inversión Estructurado', 35, 22, NULL);
INSERT INTO WF_OBJ.DIAGRAMA_NODOS (PROCESO_CL, TAREA_CL, LABEL, POSICION_X, POSICION_Y, CSS_CLASS)
VALUES (7, 22, 'Publicar Aviso Legal', 10, 10, NULL);
INSERT INTO WF_OBJ.DIAGRAMA_NODOS (PROCESO_CL, TAREA_CL, LABEL, POSICION_X, POSICION_Y, CSS_CLASS)
VALUES (8, NULL, 'Día después de la Primera Inversión', 50, 32, NULL);
INSERT INTO WF_OBJ.DIAGRAMA_NODOS (PROCESO_CL, TAREA_CL, LABEL, POSICION_X, POSICION_Y, CSS_CLASS)
VALUES (8, 25, 'Informar a la SVS Informacion para Partícipes', 10, 10, NULL);
INSERT INTO WF_OBJ.DIAGRAMA_NODOS (PROCESO_CL, TAREA_CL, LABEL, POSICION_X, POSICION_Y, CSS_CLASS)
VALUES (9, NULL, 'Creación de Garantía', 35, 32, NULL);
INSERT INTO WF_OBJ.DIAGRAMA_NODOS (PROCESO_CL, TAREA_CL, LABEL, POSICION_X, POSICION_Y, CSS_CLASS)
VALUES (9, 27, 'Creación de Garantía', 10, 10, NULL);
INSERT INTO WF_OBJ.DIAGRAMA_NODOS (PROCESO_CL, TAREA_CL, LABEL, POSICION_X, POSICION_Y, CSS_CLASS)
VALUES (9, 28, 'Enviar Custodia e Informar a la SVS', 10, 10, NULL);
INSERT INTO WF_OBJ.DIAGRAMA_NODOS (PROCESO_CL, TAREA_CL, LABEL, POSICION_X, POSICION_Y, CSS_CLASS)
VALUES (10, NULL, 'Día de la Primera Inversión', 50, 22, NULL);
INSERT INTO WF_OBJ.DIAGRAMA_NODOS (PROCESO_CL, TAREA_CL, LABEL, POSICION_X, POSICION_Y, CSS_CLASS)
VALUES (10, 23, 'Informar a la SVS Inicio de Operaciones', 10, 10, NULL);